apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bizm3nlak-go 
  janus-idp.io/tekton: bizm3nlak-go
  backstage.io/kubernetes-id: bizm3nlak-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bizm3nlak-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  